# Rankup configuration file.
# - Okx

# This is for warning you about old config versions;
# please don't change this.
version: '2.10'

ranks: # Defines ranks and their prices
- A:0
- B:10000
- C:30000
- D:75000
prestige: # Defines prestige ranks and their prices
- P1:100000
- P2:200000
messages:
  noMoneyToRankup: |- # Message to send when player doesn't have enough money to rankup
    &4&lError: &cNot enough money!
    &eYou need $%AMOUNTTOTAL%
  highestRank: '&aGood work! You''re at the highest rank - %RANK%' # Sent when the player cannot rankup anymore and prestiging is off or they are at max prestige
  highestRankToPrestige: '&aYou need to prestige to get to a higher rank!' # Sent when the player cannot rankup but can prestige
  successfulRankupPrivate: '&aYou successfully ranked up to: &d%RANK%' # Sent to the player when the player successfully runs /rankup
  successfulRankupPublic: '&a%PLAYER% &esuccessfully ranked up to: &d%RANK%' # Sent to everyone on the server when someone ranks up (configurable)
  successfulPrestigePrivate: '&aYou successfully prestiged to: &d%RANK%' # Sent to the player when the player successfully runs /prestige
  successfulPrestigePublic: '&a%PLAYER% &esuccessfully prestiged to: &d%RANK%' # Sent to everyone on the server when someone prestiges (configurable)
  notInLadder: '&cYou are not in one of the Rankup groups defined in the config' # Sent to the player when they are not in a group specified in ranks
  listRanks: # Configures how ranks are listed
    # set to 'none' to disable
    ranks:
      header: 'none'
      footer: 'none'
      default: "&r%OLDRANK% &e\xbb &r%RANK% &efor &r%AMOUNT%"
      complete: "&7%OLDRANK% &8\xbb &7%RANK% &8for &7%AMOUNT%"
      inProgress: "&c%OLDRANK% &e\xbb &c%RANK% &efor &c%AMOUNT% &e(%PERCENTDONE%%)"
    prestiges:
      header: 'none'
      footer: 'none'
      default: "&r%RANK% &efor &r%AMOUNT%"
      complete: "&7%RANK% &8for &7%AMOUNT%"
      current: "&c%RANK% &efor &c%AMOUNT%"
      inProgress: "&9%OLDRANK% &e\xbb &c9RANK% &efor &9%AMOUNT% &e(%PERCENTDONE%%)"
  rankTooLowToPrestige: '&cYou cannot prestige to %RANK%, your rank isn''t high enough' # Sent to a player when they cannot prestige
  noMoneyToPrestige: '&cYou cannot prestige to %RANK%, you need %AMOUNTTOTAL%' # Sent to the player when they don't have enough moolah to prestige
  highestPrestigeGroup: '&aGood work! You are at the highest prestige rank (%RANK%)!' # Sent to the player when they attempt to prestige but cannot
  publicMessage: true # Should we send the message successfullRankupPublic?
  publicPrestigeMessage: true # Should we send the message successfullPrestigePublic?

options:
  removePointZero: true # Should we remove the .0 at the end of prices?
  prestigeDisabled: false # Should we disable prestiging?
  prestigeToRank: A # When someone prestiges, what rank should we set them to. Case sensitive!
  prestigeAtRanks: D # At what rank can someone prestige? (can be multiple ranks, eg if you write D,E). Case sensitive!
  prestigeRankMultiplier: 1.5 # Multiply the rankup prices by this when someone prestiges (set to 1 to disable)
runCommands: # These are some examples of what you can do with runCommands.
#- CONSOLE:RANKUP:say console rankup (this will make the console run this command when a player ranks up)
#- PLAYER:RANKUP:say player rankup (this will make the player run this command when that player ranks up)
#- CONSOLE:PRESTIGE:say console prestige (this will make the console run this command when a player prestiges)
#- PLAYER:PRESTIGE:say player prestige (this will make the player run this command when that player prestiges)
#- PLAYER:B:say I ranked up to rank B (this will make the player run this command when they rank up to rank B)
#- CONSOLE:P2:say %PLAYER% prestiged to P2 (this will make the console run this command when a player prestiges to P2)

# How /rankup and /prestige should be confirmed.
confirmation:
  type: 'gui' # Options are: 'gui' or 'text' or 'none'
  areYouSureRankup: '&eAre you sure you want to rankup to &a%RANK% &efor &a%AMOUNT%&e? Type &c/rankup &eagain to confirm.' # used when type is 'text'
  areYouSurePrestige: '&eAre you sure you want to prestige to &a%RANK% &efor &a%AMOUNT%&e? Type &c/prestige &eegain to confirm.' # used when type is 'text'
  timeout: 10 # Time in seconds for a player to confirm (when type is 'text')

gui: # How should the GUI be made 
  size: 9 # The size of the GUI. Must be a multiple of nine.
  'yes': # Options specifying the 'yes i want to rankup' block
    material: EMERALD_BLOCK
    lore: ' '
    index: 0-3
    name: '&a&lConfirm'
  'no': # Options specifying the 'no i don't want to rankup - cancel' block
    material: REDSTONE_BLOCK
    lore: ' '
    index: 5-8
    name: '&cCancel'
  fill: # What block we should use to fill the spaces in the GUI
    name: ' '
    lore: ' '
    material: BLACK_STAINED_GLASS_PANE
  name:
    rankup: '&c%RANK% for %AMOUNT%' # The name of the GUI. If it is too long it will be shortened.
    prestige: '&1%RANK% for %AMOUNT%'
placeholders:
  # See the following for more information about these formats
  # https://docs.oracle.com/javase/8/docs/api/java/text/DecimalFormat.html
  rankCostFormat: '#,##0.##'
  useShortening: true # Whether we should shorten rank prices (eg turn $1000 into $1k)
  # These do not have to be single characters
  shortened:
  - 'k'
  - 'M'
  - 'B'
  - 'T'
  percentDoneFormat: '#.##'
  percentLeftFormat: '#.##'
  allowNegativePercent: false
  highestRank: 'None' # What should be used as a placeholder for ranks above the highest rank
  notInLadder: 'None' # Placeholder to use if the player is not in any of the Rankup groups
  noPrestigeRank: 'None' # Placeholder for when a player hasn't prestiged
  aliases:
  # with this you can use %rankup_nrcf% instead of %rankup_next_rank_cost_formatted%
  - 'next_rank_cost_formatted:nrcf'